---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get Vector version
    ansible.builtin.command: "vector --version"
    changed_when: false
    register: vector_version
  # - name: Assert Vector installation
  #   assert:
  #     that: "'{{ vector_version.rc }}' == '0'"
  # - name: Validate vector config file
  #   ansible.builtin.command: "vector validate --no-environment --config-yaml /etc/vector/vector.yaml"
  #   register: vector_validate
  #   changed_when: false
  # - name: Assert Vector validate config
  #   assert:
  #     that: "'{{ vector_validate.rc }}' == '0'"
  - name: Assert vector service started
    ansible.builtin.service:
      name: vector
      state: started